version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16 
    working_directory: ~/repo

jobs:
  frontend-build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install frontend dependencies
          command: cd Customer-Portal/Frontend && npm install
      - run:
          name: Start React app in development mode
          command: cd Customer-Portal/Frontend && HTTPS=true npm start  # Correct directory for npm start

  backend-deploy:  # Corrected indentation here
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install backend dependencies
          command: cd Customer-Portal/Backend && npm install  # Ensure correct directory for backend install
      - run:
          name: Start backend (Node.js/Express) server
          command: cd Customer-Portal/Backend && node server.js  # Use node instead of nodemon

workflows:
  version: 2
  build-deploy:
    jobs:
      - frontend-build
      - backend-deploy:
          requires:
            - frontend-build
