version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16 
    working_directory: ~/repo

jobs:
  frontend-build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install frontend dependencies
          command: cd App/Frontend && npm install
      - run:
          name: Start React app in development mode
          command: |
            cd App/Frontend && HTTPS=true nohup npm start &

  backend-deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Remove existing node_modules
          command: cd App/Backend && rm -rf node_modules
      - run:
          name: Install backend dependencies
          command: cd App/Backend && npm install
      - run:
          name: Install compatible bcrypt
          command: cd App/Backend && npm install bcrypt@latest
      - run:
          name: Start backend (Node.js/Express) server
          command: cd App/Backend && node server.js

  sonarqube:
    working_directory: ~/build
    docker:
      - image: sonarsource/sonar-scanner-cli
    resource_class: small
    steps:
      #- run: apk update
      #- run:  apk upgrade
      #- run:  apk --no-cache add --update openssh git curl
      - checkout
      - run: find .
      - attach_workspace:
          at: ~/workspace
      - run: |
          SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
          echo "Sonar branch value is: " $SONAR_BRANCH
          echo "Sonar org value is : "$SONAR_ORG
          sonar-scanner \
          -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
          -Dsonar.organization="$SONAR_ORG" \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.exclusions="**/android/**,**/ios/**" \
          -Dsonar.token="$SONAR_TOKEN" \
          -Dsonar.branch.name="$SONAR_BRANCH" \
          -Dsonar.sources="."

workflows:
  version: 2
  build-deploy:
    jobs:
      - frontend-build
      - backend-deploy:
          requires:
            - frontend-build
