version: 2.1

executors:
  node-executor:
    machine:
      image: ubuntu-2004:202101-01  # Use an Ubuntu VM instead of Docker
    working_directory: ~/repo

jobs:
  frontend-build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install frontend dependencies
          command: cd Customer-Portal/Frontend && npm install
      - run:
          name: Start React app in development mode
          command: cd Customer-Portal/Frontend && HTTPS=true npm start

  backend-deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install backend dependencies
          command: cd Customer-Portal/Backend && npm install
      - run:
          name: Start backend (Node.js/Express) server
          command: cd Customer-Portal/Backend && npm run dev

workflows:
  version: 2
  build-deploy:
    jobs:
      - frontend-build
      - backend-deploy:
          requires:
            - frontend-build
