version: 2.1

  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  sonarqube:
    working_directory: ~/build
    docker:
      - image: sonarsource/sonar-scanner-cli
    resource_class: small
    steps:
      - run: apk update
      - run: apk upgrade
      - run: apk --no-cache add --update openssh git curl
      - checkout
      - run: find .
      - attach_workspace:
          at: ~/workspace

workflows:
  say-hello-workflow:
    jobs:
      - say-hello