version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14 
    working_directory: ~/repo

jobs:
  frontend-build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install frontend dependencies
          command: cd Frontend && npm install
      - run:
          name: Build React app
          command: npm start
      - persist_to_workspace:
          root: ~/repo
          paths:
            - client/build

  # Job for backend (Node.js/Express)
  backend-deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install backend dependencies
          command: npm install
      - run:
          name: Start backend (Node.js/Express) server
          command: npm run dev

workflows:
  version: 2
  build-deploy:
    jobs:
      - frontend-build
      - backend-deploy:
          requires:
            - frontend-build
